### ISSUE TITLE
Convert and test diffpy.structure adapter

### ISSUE THREAD

**Issue by pavoljuhas** [diffpy/diffpy.srfit#30]
I have started update of `diffpy.structure.Structure` adapter in the [py3-adapt-structure](https://github.com/diffpy/diffpy.srfit/tree/py3-adapt-structure) branch, but it is not yet finished.  Please, complete in a PR based off the py3-adapt-structure.

TODO:
- [ ] verify all import statements from diffpy.structure (version >= 3.0a1).  Watch for lower-cased module names.
- [ ] update the `TestSGConstraints` class so it runs tests that only need diffpy.structure (currently skipped unless both pyobjcryst and diffpy.structure exist).  Change base class to `unittest.TestCase` and use the unittest `skipIf` decorator with `has_diffpy_structure` and `has_pyobjcryst` flags from `diffpy.srfit.tests.utils`.
- [ ] get test coverage of `diffpyparset` and `sgconstraints` modules to the level as in master branch.

**Comment by pavoljuhas** [comment]
@justcalamari, @chiahaoliu - can either of you help with this?

**Comment by justcalamari** [comment]
Yes, I can help.

**Comment by pavoljuhas** [comment]
@justcalamari - thank you.  When ready, please submit as a PR for the python3 branch.

**Comment by pavoljuhas** [comment]
@justcalamari - any developments on this issue?  Let me know if you have questions or need help.

**Comment by justcalamari** [comment]
@pavoljuhas - I ran into an error in testsgconstraints.py. testConstrainAsSpaceGroup() and test_ConstrainAsSpaceGroup_args gave TypeError: iter() returned non-iterator of type 'odict_values'
from the lines "for par in sgpars:" and "list(sgpars)" respectively. sgpars is type SpaceGroupParameters, the __iter__() method of which returns RecipeContainer.__iter__(). The __iter__() method of RecipeContainer returns self._parameters.values(), where self._parameters is an OrderedDict; however, the __iter__ method must return an iterator. The python 2 branched correctly use self._parameters.itervalues(), but the python 3 conversion was incorrect. The __iter__ method should instead return iter(self._parameters.values()).

I can fix this and include it in my PR with the TODOs listed above or I can put it in a separate PR. This conversion issue may be in other classes though, and it is something everybody should be aware of for the python 3 conversion.

**Comment by pavoljuhas** [comment]
> I can fix this and include it in my PR with the TODOs listed above or I can put it in a separate PR.

Good catch!  Please, submit the `__iter__` fix as a separate PR.

**Comment by pavoljuhas** [comment]
On a second thought, it is ok to fix the iter bug in the first PR, just make sure the fix is in a separate commit.

**Comment by justcalamari** [comment]
`diffpyparset` has 98.27% coverage in master and 93.97% in my py3-adapt-structure branch. The lines covered in master but not py3-adapt-structure are the methods `_getSrRealStructure` and `canAdapt`.

`_getSrRealStructure` imports from `diffpy.srreal`, which is not installed in .travis.yml, presumable because there is no python 3 version, so I think it is okay that these lines of code are skipped. `canAdapt` is only called in the function `struToParameterSet` of `diffpy.srfit.structure.__init__`. `struToParameterSet` is only called in `diffpy.srfit.pdf.basepdfgenerator`, and PDF tests are skipped in all testers because `diffpy.srreal` cannot be imported.

`sgconstraints` has 76.72% coverage in master and 71.15% in py3-adapt-structure. The lines covered in master but not py3-adapt-structure are the methods `_getLatPars`, `_getXYZPars`, and `_getADPPars`. These methods are only called in `testConstrainSpaceGroup` of `testsgconstraints`, which is skipped if `pyobjcryst` is not installed, and .travis.yml does not install `pyobjcryst`.

Is it okay that these lines are skipped because they depend on modules that are not installed?

**Comment by pavoljuhas** [comment]
> Is it okay that these lines are skipped because they depend on modules that are not installed?

Yes that is OK.  Please, create a PR towards the python3 branch.

**Comment by pavoljuhas** [comment]
Fixed with d6e78b4130d6f34d8d9e06d5d4a352b40c8f7f82.
